services:
  web:
    build: .
    ports:
      - "8080:80"
    networks:
        - devops-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword # In a real environment we'd use a env var
    networks:
        - devops-network

networks:
  devops-network:
    driver: bridge
