name: CI Pipeline - DevOps Lab

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python for installing ansible linting
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python-m pip install --upgrade pip
          pip install ansible ansible-lint docker-compose

      - name: Ansible Syntax Check
        run: |
          ansible-playbook ansible/site.yml --syntax-check

      - name: Docker Compose Syntax Check
        run: |
          docker-compose -f docker/docker-compose.yml config

      - name: Ansible Lint
        run: |
          ansible-lint ansible/site.yml
